name: Deploy to VPS via SSH

on:
  push:
    branches: [ main ]  # Change to your branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd /var/www/legal-ai-assistant
          git pull origin main

          # Backend
          cd backend
          npm install
          sudo systemctl restart legal-backend

          # Frontend
          cd ../frontend
          npm install
          npm run build

          # Optionally reload Nginx if static files updated
          sudo systemctl reload nginx
        EOF